DB::transaction(function() {
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC 3X Antiscratch')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1vA9bDr1Kbty-ysOAOpMUViXQ6nUctbcj&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Ambassador')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=15iNGpdx6z2alj4Dnqz6_z38UK4Jdld5Y&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Bird')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1nqTDI-WzG3uAzDsNwUqBZInddUMxv5UL&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Dawn45L Alloy Dual Lock Top Box with Metal Base Plate')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1cdMzT1RMMN4AZNCZ55gYyPQGngCFWW-A&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Warrior')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1eaM2wOLQRjJJUzDzGwRnfyXeI4nccsnp&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Dictator')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1Cmn9sDpKlFR-X99cnx2xsfIMTffgy-Mx&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Dictator Anti Scratch')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1n25Ifpl52G7c4OsYGvesH8mBpLadR48h&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Extraction Anti Scratch')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=15fQWsJYN5SDX7g9zU5oNqpdJCeJxstag&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Hexa Moto')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1nZLdbYbvCPlOtGzB_y4ivWVlH2CU491T&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Intruders')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1yHLvjw2Z-8kC1GbNRpwWvebhoF1I8xoc&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Tour')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1eA81Bou5h_TR0AT98T-XW8u4jEw7-4yI&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Ranger')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1Pq35LpiXjY6pLk4zORj1KfvayYKEBtBO&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Classic')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1492RybMG9VELqNMWPcTz_50W18EMLUTH&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Ghost')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1RPUUp0detGxSoTlsx2ZwCcuiL919VAO9&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC 1X')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1GnOHk7cwocaL4vbzrIfVOzH3CcxBQ6QF&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Adamantium v2')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1NWJzZYC4ftEMC6cQ3t7RjNoNjzlRSLdy&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Ghost 2.0')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1RnuAvTgEQ82r4vBWp_NC8Ir5fk320PqL&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Black Monster')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1y8hT3Ht6CpW4Gk1KpJBKOtmaWljG-m6y&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC X Demon Slayer Gyomei')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1QKwANEbc6thlxxdZU0wff-PHpU0zrTlU&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC X Demon Slayer Nezuko')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1YRZ4HIrFOnnK7-WLGio8XMZ107llV0bG&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC X Demon Slayer Tanjiro')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1Pkf7SE2RpebgRIJSvXBgXS6YC_rjrugJ&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC X Demon Slayer Wind Hashira')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1O9iCLgEoCVR5WmdLTbSgpLPVyPR_f64w&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Freedom New')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1vHRGqWQyZzSC4Vif_YQ5YpvWHPUc3Gqo&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Freedom Old')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1AExJ_vqjz_hxirwy4qjxB5V1JUP1BlrR&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('HNJ Coffer')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1jX14Y4hpb0FYSYJbnG6Kn783mm0vVBsc&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Legacy')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1wNXXJnYq7zOvBA_g8F4iSIGgSHS80AY_&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Loot Box Number Lock')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1nqyYEakzsDyOdgy1CJDYWtPgza_6lrcD&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Loot Box Key Lock')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1QmWqB3zy18K8L9MXxko-BTFKuKimybmI&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('MC Ignite')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1GxNdiw8dg7lRru_JgBxfPopA4Rxs__e4&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('MC Graphene')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1lXaVqo9CyCh6_LXrP2Mr9ykURkMH7Zbj&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Modern Tech')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1kweXnHz_muqjjeUWOj_4dWvilQm2Y3st&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Monster Old')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1Gt_cFFS2dJaSoNgJG5PuDnnL0NJq0oGZ&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Ribs')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1QveSfCUjJ8RlMK8z0x3Sz82MkcebSM9D&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Liberty')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1GVIJNWNp4fsPpWrelp-8zCtRLmj97oQj&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Secure')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=12H7COD4UyvCKkrrzhH1Osi2ihew7pqq8&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Hexalite')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1aioVA5ZsY8YV2OMirhgSlgXDG7kDZcS5&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Atmos')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1nJzmaXSWEliM05HP-FhSd9vAnJrNoymx&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Challenger')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1YVl4IUq9ifvpxZplVfiH6DJXVes4A4s2&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Chroma')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=12l6H2_3whHZ-A7jjuqR0dp6N2oVnhYJ9&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Integra')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1l8p0tRoY9ycM5pJqzwdXmV8VAWeb29mX&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Pace')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=171qjC5ZMwaHsTCrojFJa70pKYsK8nmuC&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Saga')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1hZv18lmlcJwR5DD9wiOfC7gyxeutVSBX&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Spots Daily')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1jo2u0i2QdOUKgg7Miody31ATO-2qbBP9&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC X MESUCA Winnie the Pooh')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1qprLLVqbcQhoKJ7NmwfDZBnYHXXFkzDT&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Zephyr')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1ko8KiuHy_-Sa7mjNHTTSaASQ-HGBaWRT&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Essential')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1FhVgyRaPXQjnNGLD03EW2E1Z2Umc1YEd&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Fade')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1dilSb8kHKFsHfelhLPUikQkCc25kg0n4&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Focus')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=15YHsisa8HXH8F8BaizLV_V-kpioVFPl6&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Grid Duox')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1D8uQhQYUEqEkIJVbWJWVUyaHReuegY60&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Element')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1Ovv-6O_bR1Z0u4QoPjtaLAC9lVIXbKD_&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Revolt Air')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1kpUoUIP0u1rWPEXwqFtAHjdSXR537NQz&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Whirlwind Pista')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1vfvCyaNvDRaDSCVEA2eKqAUTPJBPH4bY&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Whirlwind Runner')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1jF7kO4laIEL1pa-f42eqN3xazDSItq3e&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Honda Navi DC Monorack')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1UPSSgwx0YVbVd3C_bw_Rv4E4mL4OGnoW&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Q4 Rambo Nmax V3')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1F0y-mbQ8_domkJgZ3-wo65WqBojo6DPZ&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Titan ADV')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1O02PJpiV6RHypmfJ_StgacL7HlMsHdpj&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Metal Warrior Click')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1hIsN-JaaruJDsBkbwJDMToALR0qpF2or&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Winner X Bracket Forward')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1SIikKIxjaF4QNE2E7VX4LOUZlxSoMlgy&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('Winner X Bracket Robin')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1aGCA6XWz5Z4SveVKMm1tuCs2o4R1_sAo&sz=w400']);
  DB::table('products')->whereRaw('LOWER(product_name) = ?', [strtolower('SEC Q4 Click')])->update(['image_url' => 'https://drive.google.com/thumbnail?id=1L-PZ0v9-bIFq-uAe0JazNGOQFq-hENaM&sz=w400']);
});
echo 'Done! Images updated.';